// Code generated by "stringer -type Coin"; DO NOT EDIT.

package tapi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BRL-0]
	_ = x[BTC-1]
	_ = x[LTC-2]
	_ = x[BCH-3]
	_ = x[XRP-4]
	_ = x[ETH-5]
}

const _Coin_name = "BRLBTCLTCBCHXRPETH"

var _Coin_index = [...]uint8{0, 3, 6, 9, 12, 15, 18}

func (i Coin) String() string {
	if i >= Coin(len(_Coin_index)-1) {
		return "Coin(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Coin_name[_Coin_index[i]:_Coin_index[i+1]]
}
